#!/usr/bin/env bash
rm -f ./out ./ref
find test/tac -maxdepth 1 -name "*.mod" -print0 | xargs -0 -L1 -I{} -- sh -c "snuplc/test_ir {} >> out"
find test/tac -maxdepth 1 -name "*.mod" -print0 | xargs -0 -L1 -I{} -- sh -c "reference/4_test_ir {} >> ref"

